name: CI

on:
  workflow_call:
    inputs:
      runtime:
        required: false
        type: string
        default: bun

      build-for-check:
        required: false
        type: boolean
        default: true

      build-for-test:
        required: false
        type: boolean
        default: true

      lint:
        required: false
        type: string
        default: nr lint --if-present

      typecheck:
        required: false
        type: string
        default: nr typecheck --if-present

      usagecheck:
        required: false
        type: string
        default: nr usagecheck --if-present

      distcheck:
        required: false
        type: string
        default: nr distcheck --if-present

jobs:
  check:
    if: ${{ inputs.runtime == 'bun' || inputs.runtime == 'node' }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        if: ${{ inputs.runtime == 'bun' }}
        uses: lumirelle/workflows/setup-bun@v3

      - name: Setup Node
        if: ${{ inputs.runtime == 'node' }}
        uses: lumirelle/workflows/setup-node@v3

      - name: Build
        if: ${{ inputs.build-for-check }}
        run: nr build

      - name: Lint
        if: ${{ inputs.lint != '' }}
        run: ${{ inputs.lint }}

      - name: Type Check
        if: ${{ inputs.typecheck != '' }}
        run: ${{ inputs.typecheck }}

      - name: Usage Check
        if: ${{ inputs.usagecheck != '' }}
        run: ${{ inputs.usagecheck }}

      - name: Distribution Check
        if: ${{ inputs.distcheck != '' }}
        run: ${{ inputs.distcheck }}

  test-bun:
    if: ${{ inputs.runtime == 'bun' }}

    strategy:
      matrix:
        bun: [latest]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Bun ${{ matrix.bun }}
        if: ${{ inputs.runtime == 'bun' }}
        uses: lumirelle/workflows/setup-bun@v3
        with:
          bun-version: ${{ matrix.bun }}

      - name: Build
        if: ${{ inputs.build-for-test }}
        run: nr build

      - name: Test
        run: nr test --coverage --coverage-reporter=lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  test-node:
    if: ${{ inputs.runtime == 'node' }}

    strategy:
      matrix:
        node: [20, 22, 24, 25]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Node ${{ matrix.node }}
        if: ${{ inputs.runtime == 'node' }}
        uses: lumirelle/workflows/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Build
        if: ${{ inputs.build-for-test }}
        run: nr build

      - name: Test
        run: nr test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
