name: CI

on:
  workflow_call:
    inputs:
      runtime:
        required: false
        type: string
        default: bun

      build-for-check:
        required: false
        type: boolean
        default: false

      lint:
        required: false
        type: string
        default: nr lint

      typecheck:
        required: false
        type: string
        default: nr typecheck

      usagecheck:
        required: false
        type: string
        default: nr usagecheck

jobs:
  check:
    if: ${{ inputs.runtime == 'bun' || inputs.runtime == 'node' }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        if: ${{ inputs.runtime == 'bun' }}
        uses: lumirelle/workflows/setup-bun@v3

      - name: Setup Node
        if: ${{ inputs.runtime == 'node' }}
        uses: lumirelle/workflows/setup-node@v3

      - name: Build
        if: ${{ inputs.build-for-check }}
        run: nr build

      - name: Lint
        if: ${{ inputs.lint != '' }}
        run: ${{ inputs.lint }}

      - name: Typecheck
        if: ${{ inputs.typecheck != '' }}
        run: ${{ inputs.typecheck }}

      - name: Usagecheck
        if: ${{ inputs.usagecheck != '' }}
        run: ${{ inputs.usagecheck }}

  test:
    if: ${{ inputs.runtime == 'bun' || inputs.runtime == 'node' }}

    strategy:
      matrix:
        bun: [latest]
        node: [20, 22, 24, 25]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Bun ${{ matrix.bun }}
        if: ${{ inputs.runtime == 'bun' }}
        uses: lumirelle/workflows/setup-bun@v3
        with:
          bun-version: ${{ matrix.bun }}

      - name: Setup Node ${{ matrix.node }}
        if: ${{ inputs.runtime == 'node' }}
        uses: lumirelle/workflows/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Build
        run: nr build

      - name: Test
        run: nr test --coverage ${{ inputs.runtime == 'bun' && '--coverage-reporter=lcov' || '' }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
