name: Release Commit Dogfood

on:
  push:
    tags-ignore: ['v*']
  pull_request: {}

permissions: {}

jobs:
  release-commit:
    uses: lumirelle/workflows/.github/workflows/release-commit.yml@v2
    with:
      compact: true
      publish: false
