name: Release Commit

on:
  workflow_call:
    inputs:
      runtime:
        required: false
        type: string
        default: bun

      publish:
        required: false
        type: boolean
        default: true

      compact:
        required: false
        type: boolean
        default: false

      packages:
        required: false
        type: string
        default: ''

jobs:
  release-commit:
    if: ${{ inputs.runtime == 'bun' || inputs.runtime == 'node' }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        if: ${{ inputs.runtime == 'bun' }}
        uses: lumirelle/workflows/setup-bun@v3

      - name: Setup Node
        if: ${{ inputs.runtime == 'node' }}
        uses: lumirelle/workflows/setup-node@v3

      - name: Build
        run: nr build

      - name: Publish
        if: ${{ inputs.publish }}
        run: nlx pkg-pr-new publish ${{ inputs.runtime == 'bun' && '--bun' || '' }} ${{ inputs.runtime == 'node' && '--pnpm' || '' }} ${{ inputs.compact && '--compact' || '' }} ${{ inputs.packages}}
