name: Release Dogfood

on:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  release:
    uses: lumirelle/workflows/.github/workflows/release.yml@main
    with:
      publish: true
      packages: ./setup-bun/* ./examples/*
    permissions:
      contents: write
      id-token: write
