name: Release Dogfood

on:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  release:
    uses: lumirelle/workflows/.github/workflows/release.yml@v3
    with:
      publish: false
      packages: ./.github/* ./*
    permissions:
      contents: write
      id-token: write
