name: Release

on:
  workflow_call:
    inputs:
      runtime:
        required: false
        type: string
        default: bun

      publish:
        required: false
        type: boolean
        default: false

      packages:
        required: false
        type: string
        default: .

      tag:
        required: false
        type: string
        default: latest

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Setup Bun
        if: ${{ inputs.runtime == 'bun' }}
        uses: lumirelle/workflows/setup-bun@v3
        with:
          fetch-all: true
          install-npm: true

      - name: Setup Node
        if: ${{ inputs.runtime == 'node' }}
        uses: lumirelle/workflows/setup-node@v3
        with:
          fetch-all: true

      - name: Build
        run: nr build

      - name: Generate GitHub Changelog
        run: nlx -b changelogithub
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish (Bun)
        if: ${{ inputs.runtime == 'bun' && inputs.publish }}
        run: |
          IFS=' ' read -ra packages <<< "${{ inputs.packages }}"
          for package in ${packages[@]}; do
            (cd $package  && bun pm pack --filename "${package}/release.tgz" && bunx npm publish ./release.tgz --access public --tag ${{ inputs.tag }})
          done

      - name: Publish (Node)
        if: ${{ inputs.runtime == 'node' && inputs.publish }}
        run: pnpm publish --access public
